### ISSUE TITLE
module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1

### ISSUE THREAD

**Issue by AnhPC03** [ujsyehao/yolov3-multigpu#5]
Traceback (most recent call last):
  File "train.py", line 144, in <module>
    loss, outputs = model(imgs, targets)
  File "/home/anhnguyen/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/anhnguyen/miniconda3/envs/py36/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 146, in forward
    "them on device: {}".format(self.src_device_obj, t.device))
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cuda:1

I got above issue when ran the model on multi gpu.
Any one help me, please

**Comment by ujsyehao** [comment]
you should set gpu_devices ex: {0, 1, 3, 7}
