### ISSUE TITLE
多GPU训练报错

### ISSUE THREAD

**Issue by felix-wt** [ujsyehao/yolov3-multigpu#9]
你好，我在利用多GPU训练时出现了如下错误：
```
imgs size:  torch.Size([2, 3, 448, 448])
targets size:  torch.Size([26, 6])
learning rate:  0.0002
Traceback (most recent call last):
  File "train.py", line 136, in <module>
    loss, outputs = model(imgs, targets)
  File "/usr/local/miniconda3/envs/PyTorch-YOLOv3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/usr/local/miniconda3/envs/PyTorch-YOLOv3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 155, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/usr/local/miniconda3/envs/PyTorch-YOLOv3/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 165, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/usr/local/miniconda3/envs/PyTorch-YOLOv3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 85, in parallel_apply
    output.reraise()
  File "/usr/local/miniconda3/envs/PyTorch-YOLOv3/lib/python3.6/site-packages/torch/_utils.py", line 395, in reraise
    raise self.exc_type(msg)
IndexError: Caught IndexError in replica 1 on device 1.
Original Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/PyTorch-YOLOv3/lib/python3.6/site-packages/torch/nn/parallel/parallel_apply.py", line 60, in _worker
    output = module(*input, **kwargs)
  File "/usr/local/miniconda3/envs/PyTorch-YOLOv3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/remote-home/my/WuTong/PyTorch-YOLOv3/models.py", line 333, in forward
    x, layer_loss = module[0](x, targets, img_dim) # module[0]: yolo layer
  File "/usr/local/miniconda3/envs/PyTorch-YOLOv3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/remote-home/my/WuTong/PyTorch-YOLOv3/models.py", line 196, in forward
    ignore_thres=self.ignore_thres, # 0.5
  File "/remote-home/my/WuTong/PyTorch-YOLOv3/utils/utils.py", line 358, in build_targets
    noobj_mask[b[i], anchor_ious > ignore_thres, gj[i], gi[i]] = 0 # i is index
IndexError: index 1 is out of bounds for dimension 0 with size 1

```

**Comment by ujsyehao** [comment]
你的imgs_per_gpu设的多少？

**Comment by ujsyehao** [comment]
我已更新了readme，你可以查看下
